[tool.poetry]
name = "task-3"
version = "0.1.0"
description = ""
authors = ["lukosn <l.narog01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
